config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums
  end
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer
#  album_type :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord

  belongs_to :band,
  foreign_key: :band_id,
  class_name: :Band


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  foreign_key: :band_id,
  class_name: :Album

  def self.find_by_name(name)
    band = Band.find_by(name: name)
    if band
      return band
    else
      return nil
    end
  end


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, uniqueness: true, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :password_digest, presence: { message: 'Must provide password'}
  before_validation :ensure_session_token

  attr_reader :password


  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end

  # def self.generate_session_token

  # end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController


  def index
    @album = Album.all
    render :index
  end

  def create
    @bands = Band.all
    @album = Album.new(band_params)
    if @album.save
      render json: @album
    else
      render json: @album.errors.full_messages, status: 422
    end
  end

  def new
    render :new
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to band_album_url(@album)
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album
      @album.destroy
      redirect_to band_albums_url
    else
      redirect_to band_albums_url
    end
  end

  def album_params
    params.require(:album).permit(:title, :year, :band_id, :album_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  
  def index
    @band = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render json: @band.errors.full_messages, status: 422
    end
  end

  def new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    if @band
      @band.destroy
      redirect_to bands_url
    else
      redirect_to bands_url
    end
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login(@user)
      redirect_to bands_url
    else
      render json: ["Invalid Credentials"]
    end
  end

  def destroy
    self.current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def new
    @user = User.new
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user
    else
      render json: @user.errors.full_messages, status: 422
    end
  end


  def show
    @user = User.find_by(id:params[:id])
    if @user
      render json: @user
    else
      redirect_to users_url
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<h2>Album List</h2>

<% @album.each do |albums| %>

<%= albums.title %>
<%= albums.year %>


<% end %>

app/views/albums/new.html.erb
<h2>Add Album</h2>

<form action= "<%=band_albums_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="album_title">Album Title:
  <input id="album_title" type="text" name="album[title]">
  </label>
  <label for="band_name">Band:
    <select id="band_name" type="text" name="album[band_id]">
      <% @bands.each do |band| %>
      <option value="<%=band%>"></option>
      <% end %>
  </label>
  <label for="band_name">Album Year:
  <input id="band_name" type="text" name="album[year]">
  </label>
  <label for="band_name">Album Type:
  <input id="band_name" type="text" name="album[album_type]">
  </label>
  <input type="submit" value="Add Album">
</form>

app/views/bands/edit.html.erb
<h3>Edit Band</h3>

<form action= "<%=band_url(@band)%>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="band_name">Band Name:
  <input id="band_name" type="text" name="band[name]" value="<%=@band.name%>">
  </label>
  <input type="submit" value="Edit Band">
</form>

app/views/bands/index.html.erb
<h2>Band List</h2>

<% @band.each do |bands| %>
<%= bands.name %>

<form action="<%=edit_band_url(bands)%>" method="get">
  <input type="submit" value="Edit">
</form>

<form action="<%=band_url(bands.id)%>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Delete">
</form>

<% end %>

<br>
<form class="" action="<%=new_band_url%>" method="get">
  <input type="submit" value="Add a Band">
</form>

app/views/bands/new.html.erb
<form action= "<%=bands_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="band_name">Band Name:
  <input id="band_name" type="text" name="band[name]">
  </label>
  <input type="submit" value="Add Band">
</form>

app/views/bands/show.html.erb
<h2>Band</h2>
<%= @band.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicShare</title>
    <h1>Music Share</h1>

    <!-- <% if current_user %>
    <h2>Welcome <%= current_user.email %> </h2>
    <form action="<%=session_url%>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Logout">
    <% else %>
    <form action="<%=new_session_url%>" method="get">
      <input type="submit" value="Login">

    <% end %> -->

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>MusicShare</h1>
<style>
  body { background-color:#cccccc;}

</style>
<form action= "<%=users_url%>" method="post">
  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]">
  <label for="password">Password</label>
  <input id="password" type="text" name="user[password]">
</form>

app/views/users/show.html.erb
<h1>Hello there</h1>